export const AZ = {
  LANDING_BRAND: 'myblocate.',
  LANDING_DESCRIPTION: 'Azərbaycanda biznesinizin uğur ehtimalını öyrənin',
  LANDING_DISCLAIMER: 'Bu tətbiq süni intellektdən istifadə edir. Nəticələr məlumat tipli xarakter daşıyır və 100% dəqiq olmaya bilər.',
  LANDING_CTA: 'Başlayaq',
  HEADER_BRAND: 'myblocate.',
  MAP_INSTRUCTION: 'Yer seçmək üçün xəritəyə klikləyin',
  MODAL_TITLE: 'Bu ərazidə hansı biznes açmaq istəyirsiniz?',
  MODAL_PLACEHOLDER: 'Məsələn: Oyun klubu, Restoran, Kafe...',
  MODAL_SUBMIT: 'Təhlil et',
  MODAL_CLOSE: 'Bağla',
  LOADING_STEP_1: 'Yaxındakı obyektlər yoxlanır...',
  LOADING_STEP_2: 'Əhalinin populyasiyası hesablanır...',
  LOADING_STEP_3: 'Ortalama kirayə qiymətləri hesablanır...',
  LOADING_STEP_4: 'Trafik axını hesablanır...',
  RESULT_PROBABILITY: 'Uğur ehtimalı',
  RESULT_PROS: 'Müsbət cəhətlər',
  RESULT_CONS: 'Risklər',
  RESULT_VERDICT: 'Ümumi qiymətləndirmə',
  RESULT_RESET: 'Başqa yer təhlil et',
  HISTORY_BUTTON_LABEL: 'Tarixçə',
  HISTORY_TITLE: 'Keçmiş təhlillər',
  HISTORY_EMPTY: 'Hələ heç bir təhlil yoxdur.',
  ERROR_NO_DATA: 'Bu ərazidə kifayət qədər məlumat yoxdur. Daha məskunlaşmış bir yer sınayın.',
  ERROR_ANALYSIS_FAILED: 'Təhlil uğursuz oldu. Yenidən cəhd edin.',
  LANDING_MISSION_TITLE: 'Missiyamız',
  LANDING_MISSION_TEXT: 'Biz sahibkarlara Azərbaycanda harada biznes açmaq barədə məlumata əsaslanan qərarlar qəbul etməyə kömək edirik. Süni intellekt ilə piyada axını, rəqabət və ərazi demografiyasını təhlil edərək uğurunuzu artıracaq faydalı məlumatlar təqdim edirik.',
  LANDING_CONTACT_TITLE: 'Əlaqə',
  LANDING_CONTACT_EMAIL: 'info@myblocate.az',
  RESULT_DETAIL_TITLE: 'Ətraflı Məlumat',
  RESULT_SCORE_BREAKDOWN: 'Bal Komponenti',
  RESULT_COMPETITION: 'Rəqabət',
  RESULT_FOOT_TRAFFIC: 'Piyada Aktivliyi',
  RESULT_AREA_TYPE: 'Ərazi Tipi',
  RESULT_OSM_TITLE: 'OSM Məlumatları',
  RESULT_OSM_TOTAL: 'Tapılan müəssisə',
  RESULT_OSM_COMPETITORS: 'Rəqib',
  RESULT_OSM_AREA: 'Ərazi növü',
  RESULT_OSM_LAND: 'Ərazi istifadəsi',
  RESULT_OSM_AMENITIES: 'Yaxınlıqdakı obyektlər',
  RESULT_AREA_COMMERCIAL: 'Ticarət',
  RESULT_AREA_MIXED: 'Qarışıq',
  RESULT_AREA_RESIDENTIAL: 'Yaşayış',
  HISTORY_DETAIL_BACK: 'Geri',
  // Landing page - score section
  LANDING_SCORE_TITLE: 'Bal necə hesablanır?',
  LANDING_SCORE_SUBTITLE: 'Uğur ehtimalı 6 müstəqil amilə əsasən 0–100 arası hesablanır.',
  LANDING_SCORE_COMPETITION: 'Rəqabət',
  LANDING_SCORE_COMPETITION_SUB: 'eyni tip müəssisə',
  LANDING_SCORE_FOOT_TRAFFIC: 'İnsan Populyasiyası',
  LANDING_SCORE_AREA_TYPE: 'Ərazi Tipi',
  LANDING_SCORE_TOTAL_SHOPS: 'Ümumi Mağazalar',
  LANDING_SCORE_TRANSPORT: 'Dayanacaq & Trafik',
  LANDING_SCORE_SERVICES: 'Yaxınlıqdakı Xidmətlər',
  LANDING_SCORE_RANGE_COMPETITION: '0 – 25 bal',
  LANDING_SCORE_RANGE_FOOT_TRAFFIC: '0 – 20 bal',
  LANDING_SCORE_RANGE_AREA_TYPE: '5 – 15 bal',
  LANDING_SCORE_RANGE_TOTAL_SHOPS: '0 – 15 bal',
  LANDING_SCORE_RANGE_TRANSPORT: '0 – 15 bal',
  LANDING_SCORE_RANGE_SERVICES: '0 – 10 bal',
  LANDING_SCORE_DESC_COMPETITION: 'Eyni tip rəqib sayı azaldıqca bal artır. Hər rəqib 5 bal azaldır — minimum 2 bal.',
  LANDING_SCORE_DESC_FOOT_TRAFFIC: 'Ərazidəki əhali sıxlığı nə qədər yüksəkdirsə, potensial müştəri bazası bir o qədər böyükdür.',
  LANDING_SCORE_DESC_AREA_TYPE: 'Ticarət zonası ən yüksək balı alır, qarışıq zona orta, yaşayış zonası isə minimum bal verir.',
  LANDING_SCORE_DESC_TOTAL_SHOPS: 'Ətrafda nə qədər çox mağaza və müəssisə varsa, əhalinin alış-veriş aktivliyi bir o qədər yüksəkdir.',
  LANDING_SCORE_DESC_TRANSPORT: 'Nəqliyyat dayanacaqlarının sayı və yaxınlıqdakı yol infrastrukturu əraziyə çıxışı müəyyən edir.',
  LANDING_SCORE_DESC_SERVICES: 'Məktəb, xəstəxana, bank, aptek kimi xidmət müəssisələri insanları əraziyə çəkir və piyada axını artırır.',
  LANDING_SCORE_EXAMPLE_COMPETITION: 'Məs: 4 rəqib → 25 − 20 = 5 bal',
  LANDING_SCORE_EXAMPLE_FOOT_TRAFFIC: 'Məs: yüksək sıxlıq → 18 bal',
  LANDING_SCORE_EXAMPLE_AREA_TYPE: 'Ticarət: 15 bal · Qarışıq: 10 bal · Yaşayış: 5 bal',
  LANDING_SCORE_EXAMPLE_TOTAL_SHOPS: 'Məs: 8 müəssisə → 12 bal',
  LANDING_SCORE_EXAMPLE_TRANSPORT: 'Məs: 5 dayanacaq → 15 bal (max)',
  LANDING_SCORE_EXAMPLE_SERVICES: 'Məs: 3 xidmət növü → 8 bal',
  LANDING_SCORE_FOOTNOTE: 'Qeyd: Məzarlıq, hərbi zona, sənaye ərazisi kimi xüsusi torpaq növlərində maksimal bal avtomatik aşağı salınır.',
  // Landing page - feedback form
  LANDING_CONTACT_SUBTITLE: 'Rəy, təklif və ya sualınızı bizə göndərin.',
  FEEDBACK_NAME_PLACEHOLDER: 'Adınız (istəyə bağlı)',
  FEEDBACK_EMAIL_PLACEHOLDER: 'E-poçt (istəyə bağlı)',
  FEEDBACK_MESSAGE_PLACEHOLDER: 'Rəyinizi yazın...',
  FEEDBACK_SENDING: 'Göndərilir...',
  FEEDBACK_SEND: 'Göndər →',
  FEEDBACK_THANKS: 'Təşəkkür edirik!',
  FEEDBACK_SENT_MESSAGE: 'Rəyiniz göndərildi. Tezliklə sizinlə əlaqə saxlayacağıq.',
  FEEDBACK_ERROR: 'Göndərmə uğursuz oldu. Yenidən cəhd edin.',
  // Navigation
  NAV_HOME: 'Əsas',
  NAV_MISSION: 'Missiya',
  NAV_SCORING: 'Hesablama',
  NAV_CONTACT: 'Əlaqə',
  WARN_UNKNOWN_TYPE: 'Bu biznes növü tanınmadı. Nəticələr daha az dəqiq ola bilər.',
  MAP_ERROR: 'Xəritə yüklənmədi. Səhifəni yeniləyin.',
  // Factor breakdown labels
  FACTOR_COMPETITION: 'Rəqabət',
  FACTOR_FOOT_TRAFFIC: 'Piyada Axını',
  FACTOR_AREA_TYPE: 'Ərazi Tipi',
  FACTOR_URBAN_TIER: 'Şəhər Tipi',
  FACTOR_ACCESSIBILITY: 'Əlçatanlıq',
  FACTOR_NEARBY_SERVICES: 'Yaxınlıqdakı Xidmətlər',
  FACTOR_BUSINESS_DENSITY: 'Biznes Sıxlığı',
  RESULT_FACTOR_BREAKDOWN: 'Faktor Bölgüsü',
} as const
