export const AZ = {
  MAP_INSTRUCTION: 'Yer seçmək üçün xəritəyə klikləyin',
  MODAL_TITLE: 'Bu ərazidə hansı biznes açmaq istəyirsiniz?',
  MODAL_PLACEHOLDER: 'Məsələn: Oyun klubu, Restoran, Kafe...',
  MODAL_SUBMIT: 'Təhlil et',
  MODAL_CLOSE: 'Bağla',
  LOADING_STEP_1: 'Sahə məlumatları yüklənir...',
  LOADING_STEP_2: 'AI ilə təhlil edilir...',
  RESULT_PROBABILITY: 'Uğur ehtimalı',
  RESULT_PROS: 'Müsbət cəhətlər',
  RESULT_CONS: 'Risklər',
  RESULT_VERDICT: 'Ümumi qiymətləndirmə',
  RESULT_RESET: 'Başqa yer təhlil et',
  HISTORY_BUTTON_LABEL: 'Tarixçə',
  HISTORY_TITLE: 'Keçmiş təhlillər',
  HISTORY_EMPTY: 'Hələ heç bir təhlil yoxdur.',
  ERROR_NO_DATA: 'Bu ərazidə kifayət qədər məlumat yoxdur. Daha məskunlaşmış bir yer sınayın.',
  ERROR_ANALYSIS_FAILED: 'Təhlil uğursuz oldu. Yenidən cəhd edin.',
} as const
