export const EN = {
  LANDING_BRAND: 'myblocate',
  LANDING_DESCRIPTION: 'Discover your business success probability in Azerbaijan',
  LANDING_DISCLAIMER: 'This app uses artificial intelligence. Results are informational and may not be 100% accurate.',
  LANDING_CTA: "Let's start",
  HEADER_BRAND: 'myblocate',
  MAP_INSTRUCTION: 'Click on the map to select a location',
  MODAL_TITLE: 'What business do you want to open in this area?',
  MODAL_PLACEHOLDER: 'e.g. Game club, Restaurant, Cafe...',
  MODAL_SUBMIT: 'Analyze',
  MODAL_CLOSE: 'Close',
  LOADING_STEP_1: 'Checking nearby places...',
  LOADING_STEP_2: 'Calculating population density...',
  LOADING_STEP_3: 'Estimating average rent prices...',
  LOADING_STEP_4: 'Analyzing traffic flow...',
  RESULT_PROBABILITY: 'Success probability',
  RESULT_PROS: 'Advantages',
  RESULT_CONS: 'Risks',
  RESULT_VERDICT: 'Overall assessment',
  RESULT_RESET: 'Analyze another location',
  HISTORY_BUTTON_LABEL: 'History',
  HISTORY_TITLE: 'Past analyses',
  HISTORY_EMPTY: 'No analyses yet.',
  ERROR_NO_DATA: 'Not enough data in this area. Try a more populated location.',
  ERROR_ANALYSIS_FAILED: 'Analysis failed. Please try again.',
  LANDING_MISSION_TITLE: 'Our Mission',
  LANDING_MISSION_TEXT: 'We help entrepreneurs make data-driven decisions about where to open their business in Azerbaijan. Using AI-powered analysis of foot traffic, competition, and area demographics, we provide actionable insights to maximize your chances of success.',
  LANDING_CONTACT_TITLE: 'Contact',
  LANDING_CONTACT_EMAIL: 'info@myblocate.az',
  RESULT_DETAIL_TITLE: 'Detailed Analysis',
  RESULT_SCORE_BREAKDOWN: 'Score Breakdown',
  RESULT_COMPETITION: 'Competition',
  RESULT_FOOT_TRAFFIC: 'Foot Traffic',
  RESULT_AREA_TYPE: 'Area Type',
  RESULT_OSM_TITLE: 'OSM Data',
  RESULT_OSM_TOTAL: 'Nearby businesses',
  RESULT_OSM_COMPETITORS: 'Competitors',
  RESULT_OSM_AREA: 'Area type',
  RESULT_OSM_LAND: 'Land use',
  RESULT_OSM_AMENITIES: 'Nearby amenities',
  RESULT_AREA_COMMERCIAL: 'Commercial',
  RESULT_AREA_MIXED: 'Mixed',
  RESULT_AREA_RESIDENTIAL: 'Residential',
  HISTORY_DETAIL_BACK: 'Back',
  // Landing page - score section
  LANDING_SCORE_TITLE: 'How is the score calculated?',
  LANDING_SCORE_SUBTITLE: 'Success probability is calculated on a 0–100 scale based on 6 independent factors.',
  LANDING_SCORE_COMPETITION: 'Competition',
  LANDING_SCORE_COMPETITION_SUB: 'same type business',
  LANDING_SCORE_FOOT_TRAFFIC: 'Population Density',
  LANDING_SCORE_AREA_TYPE: 'Area Type',
  LANDING_SCORE_TOTAL_SHOPS: 'Total Shops',
  LANDING_SCORE_TRANSPORT: 'Stops & Traffic',
  LANDING_SCORE_SERVICES: 'Nearby Services',
  LANDING_SCORE_RANGE_COMPETITION: '0 – 25 pts',
  LANDING_SCORE_RANGE_FOOT_TRAFFIC: '0 – 20 pts',
  LANDING_SCORE_RANGE_AREA_TYPE: '5 – 15 pts',
  LANDING_SCORE_RANGE_TOTAL_SHOPS: '0 – 15 pts',
  LANDING_SCORE_RANGE_TRANSPORT: '0 – 15 pts',
  LANDING_SCORE_RANGE_SERVICES: '0 – 10 pts',
  LANDING_SCORE_DESC_COMPETITION: 'The fewer same-type competitors nearby, the higher the score. Each competitor reduces it by 5 points — minimum 2.',
  LANDING_SCORE_DESC_FOOT_TRAFFIC: 'The higher the population density in the area, the larger the potential customer base.',
  LANDING_SCORE_DESC_AREA_TYPE: 'Commercial zones score highest, mixed zones score medium, residential zones score minimum.',
  LANDING_SCORE_DESC_TOTAL_SHOPS: 'The more shops and businesses nearby, the higher the shopping activity of the local population.',
  LANDING_SCORE_DESC_TRANSPORT: 'The number of public transport stops and road infrastructure determines how accessible the area is.',
  LANDING_SCORE_DESC_SERVICES: 'Schools, hospitals, banks, and pharmacies attract people to the area and increase foot traffic.',
  LANDING_SCORE_EXAMPLE_COMPETITION: 'e.g. 4 competitors → 25 − 20 = 5 pts',
  LANDING_SCORE_EXAMPLE_FOOT_TRAFFIC: 'e.g. high density → 18 pts',
  LANDING_SCORE_EXAMPLE_AREA_TYPE: 'Commercial: 15 pts · Mixed: 10 pts · Residential: 5 pts',
  LANDING_SCORE_EXAMPLE_TOTAL_SHOPS: 'e.g. 8 businesses → 12 pts',
  LANDING_SCORE_EXAMPLE_TRANSPORT: 'e.g. 5 stops → 15 pts (max)',
  LANDING_SCORE_EXAMPLE_SERVICES: 'e.g. 3 service types → 8 pts',
  LANDING_SCORE_FOOTNOTE: 'Note: Special land types like cemeteries, military zones, and industrial areas automatically lower the maximum score.',
  // Landing page - feedback form
  LANDING_CONTACT_SUBTITLE: 'Send us your feedback, suggestions, or questions.',
  FEEDBACK_NAME_PLACEHOLDER: 'Your name (optional)',
  FEEDBACK_EMAIL_PLACEHOLDER: 'Email (optional)',
  FEEDBACK_MESSAGE_PLACEHOLDER: 'Write your feedback...',
  FEEDBACK_SENDING: 'Sending...',
  FEEDBACK_SEND: 'Send →',
  FEEDBACK_THANKS: 'Thank you!',
  FEEDBACK_SENT_MESSAGE: 'Your feedback has been sent. We will get back to you shortly.',
  FEEDBACK_ERROR: 'Failed to send. Please try again.',
  // Navigation
  NAV_HOME: 'Home',
  NAV_MISSION: 'Mission',
  NAV_SCORING: 'Scoring',
  NAV_CONTACT: 'Contact',
} as const
