export const EN = {
  LANDING_BRAND: 'myblocate',
  LANDING_DESCRIPTION: 'Discover your business success probability in Azerbaijan',
  LANDING_DISCLAIMER: 'This app uses artificial intelligence. Results are informational and may not be 100% accurate.',
  LANDING_CTA: "Let's start",
  HEADER_BRAND: 'myblocate',
  MAP_INSTRUCTION: 'Click on the map to select a location',
  MODAL_TITLE: 'What business do you want to open in this area?',
  MODAL_PLACEHOLDER: 'e.g. Game club, Restaurant, Cafe...',
  MODAL_SUBMIT: 'Analyze',
  MODAL_CLOSE: 'Close',
  LOADING_STEP_1: 'Loading area data...',
  LOADING_STEP_2: 'Analyzing with AI...',
  RESULT_PROBABILITY: 'Success probability',
  RESULT_PROS: 'Advantages',
  RESULT_CONS: 'Risks',
  RESULT_VERDICT: 'Overall assessment',
  RESULT_RESET: 'Analyze another location',
  HISTORY_BUTTON_LABEL: 'History',
  HISTORY_TITLE: 'Past analyses',
  HISTORY_EMPTY: 'No analyses yet.',
  ERROR_NO_DATA: 'Not enough data in this area. Try a more populated location.',
  ERROR_ANALYSIS_FAILED: 'Analysis failed. Please try again.',
  LANDING_MISSION_TITLE: 'Our Mission',
  LANDING_MISSION_TEXT: 'We help entrepreneurs make data-driven decisions about where to open their business in Azerbaijan. Using AI-powered analysis of foot traffic, competition, and area demographics, we provide actionable insights to maximize your chances of success.',
  LANDING_CONTACT_TITLE: 'Contact',
  LANDING_CONTACT_EMAIL: 'info@myblocate.az',
} as const
