export const EN = {
  LANDING_BRAND: 'myblocate',
  LANDING_DESCRIPTION: 'Discover your business success probability in Azerbaijan',
  LANDING_DISCLAIMER: 'This app uses artificial intelligence. Results are informational and may not be 100% accurate.',
  LANDING_CTA: "Let's start",
  HEADER_BRAND: 'myblocate',
  MAP_INSTRUCTION: 'Click on the map to select a location',
  MODAL_TITLE: 'What business do you want to open in this area?',
  MODAL_PLACEHOLDER: 'e.g. Game club, Restaurant, Cafe...',
  MODAL_SUBMIT: 'Analyze',
  MODAL_CLOSE: 'Close',
  LOADING_STEP_1: 'Checking nearby places...',
  LOADING_STEP_2: 'Calculating population density...',
  LOADING_STEP_3: 'Estimating average rent prices...',
  LOADING_STEP_4: 'Analyzing traffic flow...',
  RESULT_PROBABILITY: 'Success probability',
  RESULT_PROS: 'Advantages',
  RESULT_CONS: 'Risks',
  RESULT_VERDICT: 'Overall assessment',
  RESULT_RESET: 'Analyze another location',
  HISTORY_BUTTON_LABEL: 'History',
  HISTORY_TITLE: 'Past analyses',
  HISTORY_EMPTY: 'No analyses yet.',
  ERROR_NO_DATA: 'Not enough data in this area. Try a more populated location.',
  ERROR_ANALYSIS_FAILED: 'Analysis failed. Please try again.',
  LANDING_MISSION_TITLE: 'Our Mission',
  LANDING_MISSION_TEXT: 'We help entrepreneurs make data-driven decisions about where to open their business in Azerbaijan. Using AI-powered analysis of foot traffic, competition, and area demographics, we provide actionable insights to maximize your chances of success.',
  LANDING_CONTACT_TITLE: 'Contact',
  LANDING_CONTACT_EMAIL: 'info@myblocate.az',
  RESULT_DETAIL_TITLE: 'Detailed Analysis',
  RESULT_SCORE_BREAKDOWN: 'Score Breakdown',
  RESULT_COMPETITION: 'Competition',
  RESULT_FOOT_TRAFFIC: 'Foot Traffic',
  RESULT_AREA_TYPE: 'Area Type',
  RESULT_OSM_TITLE: 'OSM Data',
  RESULT_OSM_TOTAL: 'Nearby businesses',
  RESULT_OSM_COMPETITORS: 'Competitors',
  RESULT_OSM_AREA: 'Area type',
  RESULT_OSM_LAND: 'Land use',
  RESULT_OSM_AMENITIES: 'Nearby amenities',
  RESULT_AREA_COMMERCIAL: 'Commercial',
  RESULT_AREA_MIXED: 'Mixed',
  RESULT_AREA_RESIDENTIAL: 'Residential',
  HISTORY_DETAIL_BACK: 'Back',
  // Landing page - score section
  LANDING_SCORE_TITLE: 'How is the score calculated?',
  LANDING_SCORE_SUBTITLE: 'Success probability is calculated on a 0–95 scale based on 7 independent factors.',
  LANDING_SCORE_COMPETITION: 'Competition',
  LANDING_SCORE_COMPETITION_SUB: 'same type business',
  LANDING_SCORE_FOOT_TRAFFIC: 'Metro & Road Traffic',
  LANDING_SCORE_AREA_TYPE: 'Area Type',
  LANDING_SCORE_URBAN_TIER: 'Urban Tier',
  LANDING_SCORE_ACCESSIBILITY: 'Accessibility',
  LANDING_SCORE_NEARBY_SERVICES: 'Nearby Services',
  LANDING_SCORE_BUSINESS_DENSITY: 'Business Density',
  LANDING_SCORE_RANGE_COMPETITION: '0 – 22 pts',
  LANDING_SCORE_RANGE_FOOT_TRAFFIC: '0 – 20 pts',
  LANDING_SCORE_RANGE_AREA_TYPE: '5 – 13 pts',
  LANDING_SCORE_RANGE_URBAN_TIER: '1 – 10 pts',
  LANDING_SCORE_RANGE_ACCESSIBILITY: '0 – 12 pts',
  LANDING_SCORE_RANGE_NEARBY_SERVICES: '0 – 8 pts',
  LANDING_SCORE_RANGE_BUSINESS_DENSITY: '0 – 10 pts',
  LANDING_SCORE_DESC_COMPETITION: 'Fewer same-type competitors nearby means a higher score. Rivals under 200 m count fully; 200–500 m count half — maximum 22 pts.',
  LANDING_SCORE_DESC_FOOT_TRAFFIC: 'Based on the nearest metro station\'s daily ridership (0–12 pts) plus the number of major roads nearby (0–8 pts).',
  LANDING_SCORE_DESC_AREA_TYPE: 'Commercial zones score 13 pts, mixed zones 9 pts, and residential zones 5 pts.',
  LANDING_SCORE_DESC_URBAN_TIER: 'Metro city (Baku/Sumgait) scores 10 pts, city 7 pts, town 4 pts, and rural areas 1 pt.',
  LANDING_SCORE_DESC_ACCESSIBILITY: 'Number of bus stops within 500 m (0–7 pts) plus parking availability (5 pts) — maximum 12 pts.',
  LANDING_SCORE_DESC_NEARBY_SERVICES: 'Grocery stores within 500 m (0–5 pts) plus nearby amenity categories (0–3 pts) — maximum 8 pts.',
  LANDING_SCORE_DESC_BUSINESS_DENSITY: 'Business density nearby indicates local shopping activity: 50+ businesses → 10 pts, 25+ → 7 pts, 10+ → 4 pts.',
  LANDING_SCORE_EXAMPLE_COMPETITION: 'e.g. 5 competitors → 22 − 11 = 11 pts',
  LANDING_SCORE_EXAMPLE_FOOT_TRAFFIC: 'e.g. 30 000+ daily metro → 12 pts + 3 roads → 8 pts',
  LANDING_SCORE_EXAMPLE_AREA_TYPE: 'Commercial: 13 pts · Mixed: 9 pts · Residential: 5 pts',
  LANDING_SCORE_EXAMPLE_URBAN_TIER: 'Baku/Sumgait: 10 pts · City: 7 pts · Town: 4 pts',
  LANDING_SCORE_EXAMPLE_ACCESSIBILITY: 'e.g. 2 stops + parking → 5 + 5 = 10 pts',
  LANDING_SCORE_EXAMPLE_NEARBY_SERVICES: 'e.g. 2 grocery + 2 amenity types → 4 + 3 = 7 pts',
  LANDING_SCORE_EXAMPLE_BUSINESS_DENSITY: 'e.g. 30 businesses → 7 pts',
  LANDING_SCORE_FOOTNOTE: 'Note: Special land types like cemeteries, military zones, and industrial areas automatically lower the maximum score.',
  // Landing page - feedback form
  LANDING_CONTACT_SUBTITLE: 'Send us your feedback, suggestions, or questions.',
  FEEDBACK_NAME_PLACEHOLDER: 'Your name (optional)',
  FEEDBACK_EMAIL_PLACEHOLDER: 'Email (optional)',
  FEEDBACK_MESSAGE_PLACEHOLDER: 'Write your feedback...',
  FEEDBACK_SENDING: 'Sending...',
  FEEDBACK_SEND: 'Send →',
  FEEDBACK_THANKS: 'Thank you!',
  FEEDBACK_SENT_MESSAGE: 'Your feedback has been sent. We will get back to you shortly.',
  FEEDBACK_ERROR: 'Failed to send. Please try again.',
  // Navigation
  NAV_HOME: 'Home',
  NAV_MISSION: 'Mission',
  NAV_SCORING: 'Scoring',
  NAV_CONTACT: 'Contact',
  BACK_HOME: 'Home',
  MODAL_SEARCH: 'Search categories...',
  MODAL_NO_RESULTS: 'No results found',
  MODAL_SHOW_ALL: 'Show all',
  MODAL_SHOW_LESS: 'Show less',
  WARN_UNKNOWN_TYPE: 'This business type was not recognized. Results may be less accurate.',
  WARN_DOMINANT_COMPETITOR: '⚠ Dominant competitor ({name}) {dist}m away — very high competition risk for this category.',
  MAP_ERROR: 'Map failed to load. Please refresh the page.',
  RESULT_BUSINESS_TYPE: 'Business type',
  RESULT_ANALYSIS: 'Analysis',
  RESULT_OSM_BUSINESSES: 'Businesses',
  // Factor breakdown labels
  FACTOR_COMPETITION: 'Competition',
  FACTOR_FOOT_TRAFFIC: 'Foot Traffic',
  FACTOR_AREA_TYPE: 'Area Type',
  FACTOR_URBAN_TIER: 'Urban Tier',
  FACTOR_ACCESSIBILITY: 'Accessibility',
  FACTOR_NEARBY_SERVICES: 'Nearby Services',
  FACTOR_BUSINESS_DENSITY: 'Business Density',
  RESULT_FACTOR_BREAKDOWN: 'Factor Breakdown',
  RESULT_OSM_BUS_STOPS: 'Bus Stops',
  RESULT_OSM_GROCERY: 'Grocery Stores',
  RESULT_OSM_PARKING: 'Parking',
  RESULT_OSM_METRO: 'Metro Distance',
  RESULT_LOW_SCORE_WARNING: 'Success probability is low in this area. The following factors are the main risk sources:',
} as const
