// AUTO-GENERATED by scripts/build-metro-data.mjs — do not edit manually
// Source: datasets/pathways.csv + datasets/passenger_2025.csv
import { haversineMetres } from './geo'

export interface MetroStation {
  nameAz: string
  exits: Array<{ lat: number; lng: number }>
  dailyRidership: number
}

export const METRO_STATIONS: MetroStation[] = [
  {
    "nameAz": "20 Yanvar",
    "exits": [
      {
        "lat": 40.403402,
        "lng": 49.807583
      },
      {
        "lat": 40.403369,
        "lng": 49.807902
      },
      {
        "lat": 40.403537,
        "lng": 49.808488
      },
      {
        "lat": 40.40482,
        "lng": 49.807982
      },
      {
        "lat": 40.404423,
        "lng": 49.807058
      },
      {
        "lat": 40.402775,
        "lng": 49.807052
      },
      {
        "lat": 40.403242,
        "lng": 49.806938
      }
    ],
    "dailyRidership": 49019
  },
  {
    "nameAz": "28 May",
    "exits": [
      {
        "lat": 40.379712,
        "lng": 49.848843
      },
      {
        "lat": 40.38271,
        "lng": 49.846801
      }
    ],
    "dailyRidership": 50755
  },
  {
    "nameAz": "8 Noyabr",
    "exits": [
      {
        "lat": 40.402263,
        "lng": 49.819552
      },
      {
        "lat": 40.401717,
        "lng": 49.820776
      },
      {
        "lat": 40.40137,
        "lng": 49.822054
      },
      {
        "lat": 40.402646,
        "lng": 49.819923
      }
    ],
    "dailyRidership": 4281
  },
  {
    "nameAz": "Avtovağzal",
    "exits": [
      {
        "lat": 40.42176,
        "lng": 49.796061
      },
      {
        "lat": 40.421344,
        "lng": 49.795113
      },
      {
        "lat": 40.420451,
        "lng": 49.795884
      },
      {
        "lat": 40.420312,
        "lng": 49.795509
      }
    ],
    "dailyRidership": 12113
  },
  {
    "nameAz": "Azadlıq prospekti",
    "exits": [
      {
        "lat": 40.425958,
        "lng": 49.842833
      },
      {
        "lat": 40.425245,
        "lng": 49.842692
      },
      {
        "lat": 40.425272,
        "lng": 49.840899
      },
      {
        "lat": 40.425866,
        "lng": 49.840901
      }
    ],
    "dailyRidership": 21244
  },
  {
    "nameAz": "Bakmil",
    "exits": [
      {
        "lat": 40.414152,
        "lng": 49.879007
      }
    ],
    "dailyRidership": 1572
  },
  {
    "nameAz": "Cəfər Cabbarlı",
    "exits": [
      {
        "lat": 40.379585,
        "lng": 49.848716
      },
      {
        "lat": 40.379608,
        "lng": 49.849222
      }
    ],
    "dailyRidership": 3299
  },
  {
    "nameAz": "Dərnəgül",
    "exits": [
      {
        "lat": 40.424955,
        "lng": 49.860638
      },
      {
        "lat": 40.425694,
        "lng": 49.860696
      },
      {
        "lat": 40.425625,
        "lng": 49.862902
      },
      {
        "lat": 40.424839,
        "lng": 49.862609
      }
    ],
    "dailyRidership": 3308
  },
  {
    "nameAz": "Elmlər Akademiyası",
    "exits": [
      {
        "lat": 40.375083,
        "lng": 49.812417
      },
      {
        "lat": 40.37541,
        "lng": 49.811811
      },
      {
        "lat": 40.375308,
        "lng": 49.81239
      },
      {
        "lat": 40.375056,
        "lng": 49.811605
      },
      {
        "lat": 40.375105,
        "lng": 49.815491
      }
    ],
    "dailyRidership": 36946
  },
  {
    "nameAz": "Əhmədli",
    "exits": [
      {
        "lat": 40.385988,
        "lng": 49.953697
      },
      {
        "lat": 40.385957,
        "lng": 49.954227
      },
      {
        "lat": 40.384344,
        "lng": 49.954252
      },
      {
        "lat": 40.38433,
        "lng": 49.953734
      }
    ],
    "dailyRidership": 31753
  },
  {
    "nameAz": "Gənclik",
    "exits": [
      {
        "lat": 40.400468,
        "lng": 49.850587
      },
      {
        "lat": 40.401303,
        "lng": 49.852152
      },
      {
        "lat": 40.40082,
        "lng": 49.851524
      },
      {
        "lat": 40.399895,
        "lng": 49.850974
      },
      {
        "lat": 40.40056,
        "lng": 49.852542
      },
      {
        "lat": 40.399397,
        "lng": 49.850735
      }
    ],
    "dailyRidership": 43609
  },
  {
    "nameAz": "Həzi Aslanov",
    "exits": [
      {
        "lat": 40.373863,
        "lng": 49.953849
      },
      {
        "lat": 40.37395,
        "lng": 49.953447
      },
      {
        "lat": 40.374094,
        "lng": 49.953456
      },
      {
        "lat": 40.372033,
        "lng": 49.953748
      },
      {
        "lat": 40.372109,
        "lng": 49.95311
      }
    ],
    "dailyRidership": 17672
  },
  {
    "nameAz": "Xalqlar Dostluğu",
    "exits": [
      {
        "lat": 40.398585,
        "lng": 49.952052
      },
      {
        "lat": 40.398356,
        "lng": 49.95162
      },
      {
        "lat": 40.396683,
        "lng": 49.952848
      },
      {
        "lat": 40.397126,
        "lng": 49.953076
      }
    ],
    "dailyRidership": 27400
  },
  {
    "nameAz": "Xocəsən",
    "exits": [
      {
        "lat": 40.421499,
        "lng": 49.778066
      }
    ],
    "dailyRidership": 2911
  },
  {
    "nameAz": "İçərişəhər",
    "exits": [
      {
        "lat": 40.365899,
        "lng": 49.831529
      }
    ],
    "dailyRidership": 19385
  },
  {
    "nameAz": "İnşaatçılar",
    "exits": [
      {
        "lat": 40.391379,
        "lng": 49.802764
      },
      {
        "lat": 40.391391,
        "lng": 49.802163
      },
      {
        "lat": 40.388998,
        "lng": 49.802512
      },
      {
        "lat": 40.388996,
        "lng": 49.803148
      }
    ],
    "dailyRidership": 30273
  },
  {
    "nameAz": "Koroğlu",
    "exits": [
      {
        "lat": 40.419433,
        "lng": 49.919821
      },
      {
        "lat": 40.419647,
        "lng": 49.919581
      },
      {
        "lat": 40.420956,
        "lng": 49.918028
      },
      {
        "lat": 40.420251,
        "lng": 49.917757
      },
      {
        "lat": 40.420122,
        "lng": 49.916497
      },
      {
        "lat": 40.421491,
        "lng": 49.91644
      },
      {
        "lat": 40.421699,
        "lng": 49.916555
      }
    ],
    "dailyRidership": 55479
  },
  {
    "nameAz": "Qara Qarayev",
    "exits": [
      {
        "lat": 40.417506,
        "lng": 49.93554
      },
      {
        "lat": 40.417063,
        "lng": 49.935335
      },
      {
        "lat": 40.417579,
        "lng": 49.932686
      },
      {
        "lat": 40.417519,
        "lng": 49.93297
      },
      {
        "lat": 40.418048,
        "lng": 49.932773
      },
      {
        "lat": 40.417962,
        "lng": 49.933199
      }
    ],
    "dailyRidership": 23780
  },
  {
    "nameAz": "Memar Əcəmi",
    "exits": [
      {
        "lat": 40.412073,
        "lng": 49.815008
      },
      {
        "lat": 40.411792,
        "lng": 49.814919
      },
      {
        "lat": 40.410435,
        "lng": 49.815237
      },
      {
        "lat": 40.410251,
        "lng": 49.814793
      }
    ],
    "dailyRidership": 25736
  },
  {
    "nameAz": "Memar Əcəmi 2",
    "exits": [
      {
        "lat": 40.410365,
        "lng": 49.811939
      },
      {
        "lat": 40.410717,
        "lng": 49.8137
      }
    ],
    "dailyRidership": 1571
  },
  {
    "nameAz": "Neftçilər",
    "exits": [
      {
        "lat": 40.411849,
        "lng": 49.942465
      },
      {
        "lat": 40.411564,
        "lng": 49.941833
      },
      {
        "lat": 40.410543,
        "lng": 49.943487
      },
      {
        "lat": 40.410051,
        "lng": 49.943848
      },
      {
        "lat": 40.409739,
        "lng": 49.94317
      },
      {
        "lat": 40.410267,
        "lng": 49.942772
      }
    ],
    "dailyRidership": 35957
  },
  {
    "nameAz": "Nəriman Nərimanov",
    "exits": [
      {
        "lat": 40.40254,
        "lng": 49.868876
      },
      {
        "lat": 40.401952,
        "lng": 49.869499
      },
      {
        "lat": 40.402818,
        "lng": 49.8715
      },
      {
        "lat": 40.403389,
        "lng": 49.870936
      }
    ],
    "dailyRidership": 44489
  },
  {
    "nameAz": "Nəsimi",
    "exits": [
      {
        "lat": 40.424112,
        "lng": 49.824204
      },
      {
        "lat": 40.42449,
        "lng": 49.824127
      },
      {
        "lat": 40.424811,
        "lng": 49.826502
      },
      {
        "lat": 40.424415,
        "lng": 49.826474
      }
    ],
    "dailyRidership": 9554
  },
  {
    "nameAz": "Nizami",
    "exits": [
      {
        "lat": 40.37919,
        "lng": 49.830063
      }
    ],
    "dailyRidership": 18965
  },
  {
    "nameAz": "Sahil",
    "exits": [
      {
        "lat": 40.371751,
        "lng": 49.844644
      }
    ],
    "dailyRidership": 28911
  },
  {
    "nameAz": "Şah İsmayıl Xətai",
    "exits": [
      {
        "lat": 40.383066,
        "lng": 49.871971
      }
    ],
    "dailyRidership": 12923
  },
  {
    "nameAz": "Ulduz",
    "exits": [
      {
        "lat": 40.414779,
        "lng": 49.892668
      },
      {
        "lat": 40.415139,
        "lng": 49.892568
      },
      {
        "lat": 40.414882,
        "lng": 49.890251
      },
      {
        "lat": 40.414343,
        "lng": 49.890401
      }
    ],
    "dailyRidership": 8473
  }
]

/** Returns nearest metro exit distance + station ridership, or null if >2 000 m away. */
export function getNearestMetro(
  lat: number,
  lng: number,
): { distance: number; ridership: number } | null {
  let best: { distance: number; ridership: number } | null = null
  for (const station of METRO_STATIONS) {
    for (const exit of station.exits) {
      const d = haversineMetres(lat, lng, exit.lat, exit.lng)
      if (!best || d < best.distance) {
        best = { distance: Math.round(d), ridership: station.dailyRidership }
      }
    }
  }
  if (!best || best.distance > 2000) return null
  return best
}